name: build_frp

on:
  workflow_dispatch:
    inputs:
      key:
        description: key
        required: false
  schedule:
    # run at 0:30 every day
    - cron: '30 0 * * *'
  push:
    branches:
      - frp
    paths-ignore:
      - "frp/README.md"

jobs:
  frp:
    name: check update
    runs-on: ubuntu-latest
    outputs:
      update: ${{ steps.check_frp.outputs.update }}
      version: ${{ steps.check_frp.outputs.version }}
      tag: ${{ steps.check_frp.outputs.tag }}
      link: ${{ steps.check_frp.outputs.link }}
    permissions:
      contents: write

    steps:
      - uses: actions/checkout@v4
      
      - uses: actions/setup-python@v4
        with:
          python-version: '3.10'
          cache: 'pip'
      - run: pip install -r requirements.txt
      
      - name: Check version
        id: check_frp
        run: python3 main.py

      - name: commit
        if: ${{ steps.check_frp.outputs.update == 'true' }}
        run: |
          git config user.name ${{ github.actor }}
          git config user.email 19872483+maxiaowei0216@users.noreply.github.com
          git add frp/README.md
          git commit -m "[ci] frp updates to ${{ steps.check_frp.outputs.version }}"
          git push
      

  
  build:
    name: build frp
    runs-on: ubuntu-latest
    needs: frp
    permissions:
      packages: write
    env:
      UPDATE: ${{needs.frp.outputs.update}}
      VERSION: ${{needs.frp.outputs.version}}
      TAG: ${{needs.frp.outputs.tag}}
      DOWNLOAD_LINK: ${{needs.frp.outputs.link}}
      REGISTRY: ghcr.io
      IMAGE_NAME: ${{ github.actor }}/frp
    if: ${{needs.frp.outputs.update == 'true'}}
    steps:
      - uses: actions/checkout@v4
      - name: download frp package
        run: |
          wget -P ./frp ${{env.DOWNLOAD_LINK}}

      - name: Log in to the Container registry
        uses: docker/login-action@65b78e6e13532edd9afa3aa52ac7964289d1a9c1
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@9ec57ed1fcdbf14dcef7dfbe97b2010124a938b7
        with:
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}
          tags: |
            type=raw,latest
            type=raw,${{env.VERSION}}
            type=raw,${{env.TAG}}

      - name: Build and push Docker image
        uses: docker/build-push-action@f2a1d5e99d037542a71f64918e516c093c6f3fc4
        with:
          context: ./frp
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          build-args: |
            frp_version=${{ env.VERSION }}

  release:
    runs-on: ubuntu-latest
    needs: [frp, build]
    permissions:
      contents: write
    if: ${{needs.frp.outputs.update == 'true'}}
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-tags: true
          ref: frp
      - uses: ncipollo/release-action@v1
        with:
          commit: frp
          tag: frp_v${{needs.frp.outputs.version}}

  notify:
    runs-on: ubuntu-latest
    needs: [frp, release]
    if: ${{needs.frp.outputs.update == 'true'}}
    steps:
      - name: Push notify
        uses: maxiaowei0216/push-message@v0.1
        env:
          QYWX_CORP_ID: ${{ secrets.QYWX_CORP_ID }}
          QYWX_CORP_SECRET: ${{ secrets.QYWX_CORP_SECRET }}
          QYWX_AGENT_ID: 1000002
          QYWX_TO_USER: 'maxiaowei'
        with:
          server: QYWX
          message: 'frp has updated to ${{ needs.frp.outputs.version }}'
      


      

